[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
feed_protocol_example_anchor_program = "FLmBnBhUHMB3avTpwHZ6UkFJX1ca6dxzmRARN7L5Ax7d"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
